### ISSUE TITLE
Error while running the file

### ISSUE THREAD

**Issue by Nani155** [amartya-k/vision#1]
Traceback (most recent call last):
  File "C:/Users/mahe/Desktop/vision-master/main.py", line 80, in <module>
    mask=cv2.morphologyEx(mask,cv2.MORPH_CLOSE,kernalC1)
TypeError: Expected cv::UMat for argument 'kernel'

I didn't what is the error.Could you please he,lp me with the issue

**Comment by icon244** [comment]
change to kernalCl = np.ones((11,11),np.uint8)

**Comment by srushti420** [comment]
> change to kernalCl = np.ones((11,11),np.uint8)

where am I supposed to do this?
