### ISSUE TITLE
i faced some error

### ISSUE THREAD

**Issue by saurabhkumar444** [amartya-k/vision#4]
![image](https://user-images.githubusercontent.com/55131406/83275449-c785a600-a1ec-11ea-823c-8b47565a6497.png)

**Comment by amartya-k** [comment]
1. Install OpenCV using `pip install opencv-python`
2. While importing, do it like this: `from cv2 import cv2`

Additionally you can check this: https://stackoverflow.com/questions/50612169/pylint-not-recognizing-cv2-members
